### PR TITLE
Wavelength and Nonlinearity Correction 

### PR DESCRIPTION
**Pull request by sdickreuter**
I might have spotted a bug in the calculation of the wavelength, at least for the QE65000 the calculation has to be based on only the valid pixels to give the same result as with "SpectraSuite".
Also I implemented the nonlinearity correction, which is tested with the QE65000.
Only the last 2 commits are important, before them I reverted back to the upstream/master

### CODE REVIEW

**Comment by ap--** [comment]
Can split this PR into:
* one for the bugfix and
* one for the non-linearity correction
and rebase them onto the current master, with only the important changes?

Please don't include whitespace- or python3-compatibility- changes.
Thanks.

**Comment by sdickreuter** [comment]
I tried different things but I didn't find out how to do that with git, so here are two seperate patches:
(github doesn't like to append files so here is the text)

patch_bugfix:
```
--- ../python-oceanoptics_upstream/oceanoptics/base.py	2015-01-14 10:22:10.573384769 +0100
+++ oceanoptics/base.py	2015-01-16 09:40:37.732968993 +0100
@@ -120,6 +120,7 @@
         self._usb_speed = status['usb_speed']
         self._integration_time = status['integration_time']
         self._pixels = status['pixels']
+        self._valid_pixels = _OOValidPixels[model]
         self._EPspec = self._EPin1 if self._usb_speed == 0x80 else self._EPin0
         self._packet_N, self._packet_size, self._packet_func = (
                 _OOSpecConfig[model][self._usb_speed] )
@@ -131,8 +132,8 @@
         self._wl_factors = [float(self._query_information(i)) for i in range(1,5)]
         self._nl_factors = [float(self._query_information(i)) for i in range(6,14)]
         self._wl = sum( self._wl_factors[i] *
-              np.arange(self._pixels, dtype=np.float64)**i for i in range(4) )
-        self._valid_pixels = _OOValidPixels[model]
+                        (np.arange(self._valid_pixels.stop-self._valid_pixels.start, dtype=np.float64))**i for i in range(4) )
+
 
     #---------------------
     # High level functions
@@ -145,6 +146,7 @@
         ----------
         only_valid_pixels : bool, optional
             only optical active pixels are returned.
+            if false, just the pixel numbers are returned
 
         Returns
         -------
@@ -152,9 +154,9 @@
             wavelengths of spectrometer
         """
         if only_valid_pixels:
-            return self._wl[self._valid_pixels]
-        else:
             return self._wl
+        else:
+            return np.linspace(0,self._pixels-1)
```

patch _nonlinearity:
```
--- ../python-oceanoptics_upstream/oceanoptics/base.py	2015-01-14 10:22:10.573384769 +0100
+++ oceanoptics/base.py	2015-01-16 09:40:37.732968993 +0100
@@ -168,7 +170,7 @@
         only_valid_pixels : bool, optional
             only optical active pixels are returned.
         correct_nonlinearity : bool, optional
-            does nothing yet.
+            corrects for nonlinearity of CCD-Chip
         correct_darkcounts : bool, optional
             does nothing yet.
         correct_saturation : bool, optional
@@ -183,8 +185,14 @@
             data = np.array(self._request_spectrum()[self._valid_pixels], dtype=np.float64)
         else:
             data = np.array(self._request_spectrum(), dtype=np.float64)
+        if correct_nonlinearity:
+            data = data/self._calc_nonlinearity(data)
         return data
 
+    def _calc_nonlinearity(self, counts):
+        return sum( self._nl_factors[i] * counts**i for i in range(8) )
+
+
     def spectrum(self, raw=False, only_valid_pixels=True,
             correct_nonlinearity=True, correct_darkcounts=True,
             correct_saturation=True):
@@ -197,7 +205,7 @@
         only_valid_pixels : bool, optional
             only optical active pixels are returned.
         correct_nonlinearity : bool, optional
-            does nothing yet.
+            corrects for nonlinearity of CCD-Chip
         correct_darkcounts : bool, optional
             does nothing yet.
         correct_saturation : bool, optional
```

**Comment by ap--** [comment]
Thanks for the patches. The PR can't be merged like this, because of this huge commit history.
It looks like this, because on your repository, you didn't branch of this master branch, but always merged it into your code.

Regarding the code changes:
I don't understand you're reasoning behind the wavelength patch.

What does 
```
_query_status()['pixels']
```
return for your spectrometer (also which model are you using)?
And why would it be better to return the pixel indices if you don't request **only_valid_pixels=False**?

Also please open a second PR for the nonlinearity patch.

**Comment by sdickreuter** [comment]
You're welcome, I guess I should've made an extra branch for all my changes, but now its difficult ...

I found that when looking at the peaks of the fluorescent lights in the lab, they were shifted by about 5nm from their position compared with when looking at the peaks with SpectraSuite. I guess that when calculating the wavelengths from the pixels, SpectraSuite takes only valid pixels. But for the QE65000 the valid pixels start at 10 and not at zero an thus the wavenlenghts will be slightly shifted when calculated from 10-1034 as compared to 0-1024.
So if one does want to readout all pixels there wouldn't be a correct definition of the wavelengths of the pixels "out of range" of the wavelength correction.
Maybe you could also check with your spectrometer if you get the same results when looking at the spectrum of a fluorescent lamp.

**Comment by ap--** [comment]
That's interesting...
Because I did this back then with the **USB2000+**...
Can you start-up the wavelength calibration from Spectrasuite with your spectro-meter (you don't need to finish it, and screw up your calibration on the spectrometer) and check the reported pixel indices?

Until this is sorted out, this is considered a major bug.

**Comment by ap--** [comment]
Okay, seems as if the **QE65000** needs special treatment...
In the [seabreeze-library](http://sourceforge.net/projects/seabreeze/) there's the following piece of code:

``` {c++}
/* This function has to be overridden to make the intercept of the
 * calibration polynomial correspond to detector pixel 10.  This is due to
 * some legacy calibration issues.
 */
vector<double> *WavelengthEEPROMSlotFeature_QE65000::computeWavelengths(
        double polynomial[], int length) {

    vector<double> *retval = new vector<double>(this->numberOfPixels);
    unsigned int i;

    Polynomial<double> *calibration = new Polynomial<double>(polynomial, length);

    /* Evaluate the given polynomial to generate the wavelength array. */
    for(i = 0; i < this->numberOfPixels; i++) {
        /* Shift the evaluation by ten pixels */
        (*retval)[i] = calibration->evaluate(i - 10.0);
    }
    delete calibration;
    return retval;
}
```
So we need to fix this only for the **QE65000**.

**Comment by ap--** [comment]
6af3eac should fix this issue.

**Comment by sdickreuter** [comment]
Ahh ! Perfect,  special cases are the worst :)

**Pull request closed without merging**
